// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/blue-tape/blue-tape.d.ts
declare module 'blue-tape' {
	import tape = require('tape');
	export = tape;
}